on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Deploy to Azure

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./function-app
  AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RG }}
  AZURE_FUNCTION_APP_NAME: ${{ vars.FUNCTION_APP_NAME }}
  AZURE_APP_SERVICE_PLAN_NAME: ${{ vars.APP_SERVICE_PLAN_NAME }}
  AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
  AZURE_WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
  AZURE_KEY_VAULT_NAME: ${{ vars.KEY_VAULT_NAME }}
  AZURE_NEXTDNS_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
  AZURE_NEXTDNS_PROFILE_ID: ${{ vars.NEXTDNS_PROFILE_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: ./infra/main.bicep
        parameters: >
          functionAppName=${{ vars.FUNCTION_APP_NAME }}
          appServicePlanName=${{ vars.APP_SERVICE_PLAN_NAME }}
          storageAccountName=${{ vars.STORAGE_ACCOUNT_NAME }}
          workspaceName=${{ vars.WORKSPACE_NAME }}
          keyVaultName=${{ vars.KEY_VAULT_NAME }}
          nextDnsApiKey=${{ secrets.NEXTDNS_API_KEY }}
          nextDnsProfileId=${{ vars.NEXTDNS_PROFILE_ID }}
          keyVaultSecretsOfficerObjectId=${{ vars.KEY_VAULT_SECRETS_OFFICER_OBJECT_ID }}
          logAnalyticsWorkspaceKey=${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
        failOnStdErr: false

  deploy-function:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Function App code
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ vars.FUNCTION_APP_NAME }}
        package: ./function-app
        scm-do-build-during-deployment: false
